language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot

install:
  - composer install

script:
  - composer standards
  - composer unit-test
  - composer analyze

after_success:
  - bash <(curl -s https://codecov.io/bash)
