name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHPCodeSniffer
      run: composer standards

    - name: Psalm
      run: composer psalm

    - name: PHPUnit
      run: composer unit-test
